version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - 80:80
  node-docker:
    build:
      context: .
      args:
        NODE_ENV: production
    environment:
      - NODE_ENV=production
    command: node app.js