version: '3'
services:
#service1 nginx
  nginx:
    image: nginx:stable-alpine
    ports:
      - "3000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./html:/usr/share/nginx/html
#service2 node image
  node-docker:
    build: .
    image: ichangai1993/node-docker
    environment:
      - PORT=3000
    depends_on:
      - mongo  
#service3 mongo image
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=ichangai
      - MONGO_INITDB_ROOT_PASSWORD=mypassword
    volumes:
      - mongo-db:/data/db
#service4 redis image
  redis:
    image: redis
  
volumes:
  mongo-db:   