version: '3'
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "3000:80"
  node-docker:
    build:
      context: .
      args:
        NODE_ENV: development
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - MONGO_USER=ichangai
      - MONGO_PASSWORD=mypassword
      - SESSION_SECRET=secret
    command: npm run dev
  #Mongo service  
  mongo:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=ichangai
      - MONGO_INITDB_ROOT_PASSWORD=mypassword
        